export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const NOTEBOOKS_DELETE_REQUEST = 'NOTEBOOKS_DELETE_REQUEST'
export const NOTEBOOKS_DELETE_SUCCESS = 'NOTEBOOKS_DELETE_SUCCESS'
export const NOTEBOOKS_DELETE_FAIL = 'NOTEBOOKS_DELETE_FAIL'

export const NOTEBOOKS_UPDATE_REQUEST = 'NOTEBOOKS_UPDATE_REQUEST'
export const NOTEBOOKS_UPDATE_SUCCESS = 'NOTEBOOKS_UPDATE_SUCCESS'
export const NOTEBOOKS_UPDATE_FAIL = 'NOTEBOOKS_UPDATE_FAIL'

export const NOTEBOOKS_CREATE_REQUEST = 'NOTEBOOKS_CREATE_REQUEST'
export const NOTEBOOKS_CREATE_SUCCESS = 'NOTEBOOKS_CREATE_SUCCESS'
export const NOTEBOOKS_CREATE_FAIL = 'NOTEBOOKS_CREATE_FAIL'

export const GET_ALL_NOTE_REQUEST = 'GET_ALL_NOTE_REQUEST'
export const GET_ALL_NOTE = 'GET_ALL_NOTE'
export const GET_ALL_NOTE_SUCCESS = 'GET_ALL_NOTE_SUCCESS'
export const GET_ALL_NOTE_FAIL = 'GET_ALL_NOTE_FAIL'

// export const GET_NOTE_BY_ID = 'GET_NOTE_BY_ID'
// export const GET_NOTE_BY_ID_SUCCESS = 'GET_NOTE_BY_ID_SUCCESS'
// export const GET_NOTE_BY_ID_FAIL = 'GET_NOTE_BY_ID_FAIL'


